services:
  mysql:
    image: mysql:8.0
    container_name: sqlflamegraph-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: sqlflamegraph
      MYSQL_USER: ${MYSQL_USER:-flamegraph}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-flamegraph}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  sqlflamegraph:
    build: .
    container_name: sqlflamegraph-app
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: ${MYSQL_USER:-flamegraph}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-flamegraph}
      MYSQL_DATABASE: sqlflamegraph
      MYSQL_PORT: 3306
    ports:
      - "80:80"
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data: 